In [10]:
import numpy as np
import re

In [11]:
sentences = open('sentences.txt', 'r')

In [12]:
# make the list of all lines in lowercase
list_of_lines = []
for line in sentences:
    list_of_lines.append(line.lower())

In [13]:
# in this list break up all lines on separate words
list_of_words = []
for line in list_of_lines:
    words_in_line = re.split('[^a-z]', line)    # Create the list of all words, it consists repeats and ''
    for word in words_in_line:
        if word not in list_of_words and word != '':
            list_of_words.append(word)         # In this list we have only exclusive words

In [14]:
len(list_of_words)

254

In [15]:
# make indexation of words from list_of_words
words_index_dict = {}
index = 0         # initial index of words
for word in list_of_words:
    words_index_dict[word] = index
    index +=1     # increase index by 1 for the next word indexation

In [16]:
# Create the matrix with size 22x254, where 22- number of sentences(lines) and 254- quantity of all words 
matrix_of_words = np.zeros((22, 254))

In [17]:
matrix_of_words

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
len(matrix_of_words[0])

254

In [18]:
i= -1
for line in list_of_lines:
    i += 1
    words_of_line = re.split('[^a-z]', line)
    for word in words_of_line:
        if word != '':
            matrix_of_words[i, words_index_dict[word]] +=1    # in line 'i' increase the weight +1 of column 
                                                              # with index of word from words_index_dict 
  

In [14]:
matrix_of_words

array([[1., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 1., 1.]])

In [30]:
matrix_of_words[1,:]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 2., 2., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [20]:
from scipy.spatial import distance
distance.cosine(matrix_of_words[0,:], matrix_of_words[4,:])

0.7770887149698589

In [21]:
# Calculate the Cosine distance between vectors of different lines of matrix_of_words
distance_betwen_sentences = {}
for num in range(0,22):
    distance_betwen_sentences[num] = distance.cosine(matrix_of_words[0,:], matrix_of_words[num,:])

In [22]:
distance_betwen_sentences

{0: 0.0,
 1: 0.9527544408738466,
 2: 0.8644738145642124,
 3: 0.8951715163278082,
 4: 0.7770887149698589,
 5: 0.9402385695332803,
 6: 0.7327387580875756,
 7: 0.9258750683338899,
 8: 0.8842724875284311,
 9: 0.9055088817476932,
 10: 0.8328165362273942,
 11: 0.8804771390665607,
 12: 0.8396432548525454,
 13: 0.8703592552895671,
 14: 0.8740118423302576,
 15: 0.9442721787424647,
 16: 0.8406361854220809,
 17: 0.956644501523794,
 18: 0.9442721787424647,
 19: 0.8885443574849294,
 20: 0.8427572744917122,
 21: 0.8250364469440588}